alpha: 0.01
batch_size: 100
conv_kernel: 4
conv_stride: 1
embedding_dim: 30
group_size: 10
idx: 0
jump: 1
length_scale: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args: [f8, 0, 1]
  state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
- !!binary |
  AAAAAAAA4D8=
n_channels: [50, 30, 10]
n_epochs: 100
plot: false
pool_kernel: 1
reg_lambda: 0.01
validation_split: 0.5
window: 20
